/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary": "#e040a0",
        "on-primary": "#ffffff",
        "primary-container": "#f080c0",
        "primary-fixed": "#ffd6ee",
        "primary-fixed-dim": "#f0a0cc",
        "on-primary-fixed-variant": "#a02070",
        "secondary": "#7c52aa",
        "on-secondary": "#ffffff",
        "secondary-container": "#eedcff",
        "secondary-fixed": "#eedcff",
        "secondary-fixed-dim": "#c8a8e8",
        "tertiary": "#0096cc",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#40c0ee",
        "tertiary-fixed": "#c8eaff",
        "tertiary-fixed-dim": "#80d0f0",
        "background": "#fef7ff",
        "surface": "#fef7ff",
        "surface-dim": "#e0d6e0",
        "surface-bright": "#fef7ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fbf2fb",
        "surface-container": "#f8eef8",
        "surface-container-high": "#f2e8f2",
        "surface-container-highest": "#ece2ec",
        "surface-variant": "#f2e8f2",
        "on-surface": "#2e1a28",
        "on-surface-variant": "#604868",
        "outline": "#907898",
        "outline-variant": "#dcc8e0",
        "inverse-surface": "#2e1a28",
        "inverse-on-surface": "#fef7ff",
        "inverse-primary": "#f0a0cc",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["DM Sans", "sans-serif"],
        headline: ["DM Sans", "sans-serif"],
      },
      boxShadow: {
        "candy-pink": "0 8px 24px rgba(224, 64, 160, 0.2)",
        "candy-purple": "0 8px 24px rgba(124, 82, 170, 0.2)",
        "candy-blue": "0 8px 24px rgba(0, 150, 204, 0.2)",
        "candy-pink-lg": "0 16px 48px rgba(224, 64, 160, 0.3)",
      },
      animation: {
        "bounce-subtle": "bounce-subtle 2s ease-in-out infinite",
        "float": "float 6s ease-in-out infinite",
        "pulse-slow": "pulse 4s ease-in-out infinite",
      },
      keyframes: {
        "bounce-subtle": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-6px)" },
        },
        float: {
          "0%": { transform: "translateY(0px) rotate(0deg)" },
          "50%": { transform: "translateY(-20px) rotate(2deg)" },
          "100%": { transform: "translateY(0px) rotate(0deg)" },
        },
      },
    },
  },
  plugins: [],
}